packages:
  - "apps/*"
  - "lib/*"

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  esbuild: true
  lefthook: true
  msw: true
  sharp: true

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.9'
  - '@turbo/darwin-arm64@2.10.9'
  - '@turbo/linux-64@2.10.9'
  - '@turbo/linux-arm64@2.10.9'
  - '@turbo/windows-64@2.10.9'
  - '@turbo/windows-arm64@2.10.9'
  - '@types/node@26.2.0'
  - fastify@5.11.3
  - react-hook-form@7.85.0
  - turbo@2.10.9
  - '@scalar/client-side-rendering@0.3.6'
  - '@scalar/fastify-api-reference@1.64.1'
  - '@scalar/helpers@0.10.0'
  - '@scalar/json-magic@0.12.20'
  - '@scalar/openapi-parser@0.28.12'
  - '@scalar/openapi-upgrader@0.2.13'
  - '@scalar/schemas@0.8.1'
  - '@scalar/types@0.17.1'
